/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicalapp;

import java.time.Duration;
import java.util.Date;
import medicalapp.data.Appointment;
import static medicalapp.data.Appointment.insertAppointment;
import medicalapp.data.Doctor;
import medicalapp.data.Patient;

public class Schedule {

    //TO BE TESTED
    //In GUI options of addresses should be displayed/generated when entering firstname and lastname. This addresses
    //common patient names. 
    //Doctor name is concatenated. 
    //Purpose may be left optionally blank as "".
    public static void createAppointment(String patientFirstName, String patientLastName,
            String address, String doctorName, Date date, String purpose) {

        Appointment appointment = null;

        appointment.setAppointmentID(9000); //arbitrary parameter since ID is autogenerated in Appointment class
        appointment.setDate(date);
        appointment.setPatientID(Patient.getPatient(patientFirstName, patientLastName, address)
                .getPatientID());

        //splitting doctor's full name into parts.
        String[] docFullName = doctorName.split(" ");
        String firstName = docFullName[0]; 
        String lastName = docFullName[1]; 

        appointment.setDoctorID(Doctor.getDoctor(firstName, lastName).getDoctorID()); //expect bugs regarding doctors with common names
        appointment.setDuration(Duration.ofMinutes(15)); //Default duration of 15 minutes
        appointment.setReferringGP("TBA"); //Filled in upon checkin.
        appointment.setPurpose(purpose);
        appointment.setExpired(false);

        insertAppointment(appointment);

    }

    public static void updateAppointment() {

    }

    public static void checkInPatient(String referringGP) {
        
        
        //appointment.setReferringGP(referringGP);
    }
}
